#!/bin/sh

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

wlan_ifc=""
wifi_restart=1

logger -t "ffwizard_autoconf" "ubus call network.wireless status"
wifi_data=`ubus call network.wireless status`
json_load "$wifi_data"
json_get_keys wifi_res
for i in $wifi_res ; do
	json_select $i
	json_get_var wifi_disabled disabled
	if [ $wifi_disabled == 1 ] ; then
		logger -t "ffwizard_autoconf" "wifi $i is disabled. set enable"
		uci set wireless.$i.disabled=0
		uci set wireless.$i.country=00
		#uci commit wireless
	else
		logger -t "ffwizard_autoconf" "wifi $i allready enabled leave it untouch"
		wifi_restart=0
	fi
	json_select ".."
done

json_cleanup

if [ $wifi_restart == 1 ] ; then
	logger -t "ffwizard_autoconf" "wifi restart and sleep 20s"
	#FIXME do it with ubus call and list
	/sbin/wifi restart
	/bin/sleep 20
	logger -t "ffwizard_autoconf" "ubus call network.wireless status"
	wifi_data=`ubus call network.wireless status`
	json_load "$wifi_data"
	json_get_keys wifi_res
	for i in $wifi_res ; do
		json_select $i
		json_get_var wifi_disabled disabled
		if [ $wifi_disabled == 0 ] ; then
			wlan_ifc="$wlan_ifc $i"
		fi
		json_select ".."
	done
fi

json_cleanup

for ifc in $wlan_ifc ; do
	logger -t "ffwizard_autoconf" "ubus call iwinfo $ifc scan"
	scan_data=$(ubus call iwinfo scan '{ "device": "'$ifc'" }')
	json_load "$scan_data"
	json_select results
	json_get_keys scan_res
	quality=0
	ssid=""
	bssid=""
	channel=""
	for i in $scan_res ; do
		json_select $i
		json_select encryption
		json_get_var sta_encryption enabled
		json_select ".."
		if [ $sta_encryption == 0 ] ; then
			json_get_var sta_mode mode
			if [ $sta_mode == "Ad-Hoc" ] ; then
				json_get_var sta_ssid ssid
				if echo "$sta_ssid" | grep -q "freifunk\.net" ; then
					json_get_var sta_quality quality
					if [ $sta_quality -gt $quality ] ; then
						quality=$sta_quality
						json_get_var sta_bssid bssid
						json_get_var sta_channel channel
						json_get_var sta_signal signal
						json_get_var sta_quality_max quality_max
						ssid=$sta_ssid
						bssid=$sta_bssid
						channel=$sta_channel
					fi
				fi
			fi
		fi
		json_select ".."
	done
	json_cleanup
	logger -t "ffwizard_autoconf" "scan result for $ifc ssid: $ssid bssid: $bssid channel: $channel"
	if ! uci_get ffwizard $ifc >/dev/null ; then
		uci_add ffwizard wifi "$ifc"
	fi
	phy_idx=$(echo $ifc | cut -b6)
	uci_set ffwizard "$ifc" phy_idx $phy_idx
	uci_set ffwizard "$ifc" ssid $ssid
	uci_set ffwizard "$ifc" bssid $bssid
	uci_set ffwizard "$ifc" channel $channel
	uci_set ffwizard "$ifc" olsr_mesh 1
	uci_set ffwizard ffwizard enabled 1
	uci commit ffwizard
	/etc/init.d/ffwizard start
done
