#!/bin/sh

if ! [ -f /etc/config/luci_olsrr ] ; then
    uci -q batch <<-EOF >/dev/null
	add luci_olsr general
    set luci_olsr.general=olsr
	set luci_olsr.general.resolve=1
	set luci_olsr.general.domain="olsr"
	commit luci_olsr
EOF
else
    if ! uci -q get luci_olsr.general.domain >/dev/null ; then
        uci set luci_olsr.general.domain="olsr"
    fi
fi
