#!/bin/sh

. /lib/functions.sh

setup_ether() {
	local cfg="$1"
	config_get enabled $cfg enabled "0" 2>/dev/null
	[ "$enabled" == "0" ] && return
	config_get babel_mesh $cfg babel_mesh "0"
	[ "$babel_mesh" == "0" ] && return
	babel_enabled=1
}

setup_wifi() {
	local cfg="$1"
	config_get enabled $cfg enabled "0" 2>/dev/null
	[ "$enabled" == "0" ] && return
	config_get babel_mesh $cfg babel_mesh "0"
	[ "$babel_mesh" == "0" ] && return
	babel_enabled=1
}

addrc() {
    local cmd="$1"
    grep -v exit /etc/rc.local > /tmp/rc.local
    echo "$cmd" >> /tmp/rc.local
    echo 'exit 0' >> /tmp/rc.local
    mv /tmp/rc.local /etc/rc.local
    $cmd
}

get_seed() {
	dd if=/dev/urandom bs=2 count=1 2>&- | hexdump | if read -r line
	then
		echo "0x${line#* }"
	fi
}

babel_enabled=0
#Setup ether and wifi
config_load ffwizard
config_foreach setup_ether ether
config_foreach setup_wifi wifi

if [ "$babel_enabled" == "0" ] ; then
	if [ -s /etc/rc.d/S*babeld ] ; then
		/etc/init.d/babeld disable
	fi
	crontab -l | grep -q 'babelneighbor2hosts' && crontab -l | sed -e '/.*babelneighbor2hosts.*/d' | crontab -
	crontab -l | grep -q 'babelnode2hosts' && crontab -l | sed -e '/.*babelnode2hosts.*/d' | crontab -
	crontab -l | grep -q 'babeldns64' && crontab -l | sed -e '/.*babeldns64.*/d' | crontab -
	crontab -l | grep -q 'babel-dyn-addr' && crontab -l | sed -e '/.*babel-dyn-addr.*/d' | crontab -
	sed -e '/.*babeld restart.*/d' -i /etc/rc.local
else
	crontab -l | grep -q 'babelneighbor2hosts' || \
		echo "*/5 * * * *     /usr/sbin/babelneighbor2hosts.sh" >> /etc/crontabs/root
	SEED=$(get_seed)
	MIN1="$((SEED % 29))"
	MIN2="$((MIN1 + 30))"
	crontab -l | grep -q 'babelnode2hosts' || \
		echo "$MIN1,$MIN2 * * * *  /usr/sbin/babelnode2hosts.sh 2000" >> /etc/crontabs/root
	crontab -l | grep -q 'babeldns64' || \
		echo "*/15 * * * *    /usr/sbin/babeldns64.sh" >> /etc/crontabs/root
	crontab -l | grep -q 'babel-dyn-addr' || \
		echo "*/8 * * * *    /usr/sbin/babel-dyn-addr.sh" >> /etc/crontabs/root

	if ! grep -q "/etc/init.d/babeld" /etc/rc.local ; then
		addrc '( sleep 60 ; /etc/init.d/babeld restart ) &'
	fi

fi
exit 0