#!/bin/sh

. /lib/functions.sh

uci_add_list() {
	local PACKAGE="$1"
	local CONFIG="$2"
	local OPTION="$3"
	local VALUE="$4"

	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} add_list "$PACKAGE.$CONFIG.$OPTION=$VALUE"
}

# Set Hostname
if [ "$(uci_get system @system[0] hostname)" == "OpenWrt" ]; then
	rand="$(echo -n $(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4))"
	rand="$(printf "%d" "0x$rand")"
	hostname="OpenWrt-$rand"
	uci_set system @system[0] hostname "$hostname"
	#add ipv6 ntp server. can remove if dig AAAA 0.openwrt.pool.ntp.org is true
	uci_add_list system ntp server "2.pool.ntp.org"
	uci_commit system
	uci_set ffwizard ffwizard hostname "$hostname"
	uci_commit ffwizard
	echo "$hostname" > /proc/sys/kernel/hostname
	#Load uhttpd config
	config_load uhttpd
	config_get crtfile main cert
	config_get keyfile main key
	[ -f "$crtfile" ] && rm -f "$crtfile"
	[ -f "$keyfile" ] && rm -f "$keyfile"
	uci_set uhttpd defaults country "DE"
	uci_set uhttpd defaults state "Berlin"
	uci_set uhttpd defaults location "uncertain"
	uci_set uhttpd defaults commonname "$hostname"
	[ -f /usr/lib/lua/luci/sgi/uhttpd.lua ] && \
	uci_set uhttpd main lua_prefix "/luci"
	[ -f /usr/lib/lua/luci/sgi/uhttpd.lua ] && \
	uci_set uhttpd main lua_handler "/usr/lib/lua/luci/sgi/uhttpd.lua"
	uci_commit uhttpd

	# add dns entry frei.funk
	#uci_add dhcp domain frei_funk
	#uci_set dhcp frei_funk name "frei.funk"
	#uci_set dhcp frei_funk ip "192.168.42.1"
	# add dns entry frei.funk for ipv6
	uci_add dhcp domain frei_funk_ipv6
	uci_set dhcp frei_funk_ipv6 name "frei.funk"
	uci_set dhcp frei_funk_ipv6 ip "$(uci get network.globals.ula_prefix | cut -d '/' -f 1)1"
	uci_commit dhcp

	uci_set network lan ipaddr "192.168.42.1"
	#uci_set network lan dns "85.214.20.141 213.73.91.35 194.150.168.168 2001:4ce8::53 2001:910:800::12"
	# https://nat64.dresel.systems/ "Service eingestellt...  "
	#uci_set network lan dns "2a0b:f4c0:4d:53::1 2a01:4f8:221:2d08::213"
	# https://nat64.net/
	uci_remove network lan dns
	uci_add_list network lan dns "2a00:1098:2c::1"
	uci_add_list network lan dns "2a01:4f8:c2c:123f::1"
	uci_add_list network lan dns "2a00:1098:2b::1"
	uci_commit network

fi

# Remove disable parts of freifunk-common
/etc/init.d/freifunk disable
grep -v '/usr/sbin/ff_olsr_watchdog' /etc/crontabs/root > /etc/crontabs/root_new
mv /etc/crontabs/root_new /etc/crontabs/root

if [ -f /usr/sbin/olsrneighbor2hosts.sh ] ; then
	grep -q "olsrneighbor2hosts.sh" /etc/crontabs/root || \
	echo "*/5 * * * *     olsrneighbor2hosts.sh > /tmp/olsrneighbor2hosts.tmp && mv /tmp/olsrneighbor2hosts.tmp /tmp/hosts/olsrneighbor || rm /tmp/olsrneighbor2hosts.tmp" >> /etc/crontabs/root
fi
if [ -f /usr/sbin/olsrnode2hosts.sh ] ; then
	grep -q "olsrnode2hosts.sh" /etc/crontabs/root || \
	echo "*/10 * * * *     olsrnode2hosts.sh > /tmp/olsrnode2hosts.tmp && mv /tmp/olsrnode2hosts.tmp /tmp/hosts/olsrnode || rm /tmp/olsrnode2hosts.tmp" >> /etc/crontabs/root
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ffwizard[-1]
	add ucitrack ffwizard
	set ucitrack.@ffwizard[-1].init=ffwizard
	commit ucitrack
EOF
