#!/bin/sh

. /lib/functions.sh

uci_add_list() {
	local PACKAGE="$1"
	local CONFIG="$2"
	local OPTION="$3"
	local VALUE="$4"

	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} add_list "$PACKAGE.$CONFIG.$OPTION=$VALUE"
}

log_kadnode() {
	logger -s -t ffwizard_kadnode $@
}

setup_kadnode() {
	local cfg="$1"
	local hostname="$2"
	uci_remove kadnode $cfg value_id
	uci_add_list kadnode $cfg value_id "$hostname"
	uci_set kadnode $cfg enabled '1'
	uci_set kadnode $cfg mode 'ipv6'
}

setup_dnsmasq() {
	local cfg="$1"
	uci_remove dhcp $cfg server
	uci_add_list dhcp $cfg server '/p2p/::1#3535'
}

#Load ffwizard config
config_load ffwizard

# Set Hostname
config_get hostname ffwizard hostname "lede"

#Load kadnode config
config_load kadnode
#Setup kadnode
config_foreach setup_kadnode kadnode "$hostname"

uci_commit kadnode
uci_commit dhcp
