#!/bin/sh

. /lib/functions.sh

uci_add_list() {
	local PACKAGE="$1"
	local CONFIG="$2"
	local OPTION="$3"
	local VALUE="$4"

	/sbin/uci ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} add_list "$PACKAGE.$CONFIG.$OPTION=$VALUE"
}

# Set Hostname
if [ "$(uci_get system @system[0] hostname)" == "OpenWrt" ]; then
	rand="$(echo -n $(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4))"
	rand="$(printf "%d" "0x$rand")"
	hostname="OpenWrt-$rand"
	uci_set system @system[0] hostname "$hostname"
	#add ipv6 ntp server. can remove if dig AAAA 0.openwrt.pool.ntp.org is true
	uci_add_list system ntp server "2.pool.ntp.org"
	uci_commit system
	uci_set ffwizard ffwizard hostname "$hostname"
	uci_commit ffwizard
	echo "$hostname" > /proc/sys/kernel/hostname
	#Load uhttpd config
	config_load uhttpd
	config_get crtfile main cert
	config_get keyfile main key
	[ -f "$crtfile" ] && rm -f "$crtfile"
	[ -f "$keyfile" ] && rm -f "$keyfile"
	uci_set uhttpd px5g country "DE"
	uci_set uhttpd px5g state "Berlin"
	uci_set uhttpd px5g location "uncertain"
	uci_set uhttpd px5g commonname "$hostname"
	[ -f /usr/lib/lua/luci/sgi/uhttpd.lua ] && \
	uci_set uhttpd main lua_prefix "/cgi-bin/luci"
	[ -f /usr/lib/lua/luci/sgi/uhttpd.lua ] && \
	uci_set uhttpd main lua_handler "/usr/lib/lua/luci/sgi/uhttpd.lua"
	uci_commit uhttpd

	# add dns entry frei.funk
	uci_add dhcp domain frei_funk
	uci_set dhcp frei_funk name "frei.funk"
	uci_set dhcp frei_funk ip "192.168.42.1"
	# add dns entry frei.funk for ipv6
	uci_add dhcp domain frei_funk_ipv6
	uci_set dhcp frei_funk_ipv6 name "frei.funk"
	uci_set dhcp frei_funk_ipv6 ip "$(uci get network.globals.ula_prefix | cut -d '/' -f 1)1"
	uci_commit dhcp

	uci_set network lan ipaddr "192.168.42.1"
	uci_set network lan dns "85.214.20.141 213.73.91.35 194.150.168.168 2001:4ce8::53 2001:910:800::12"
	uci_commit network

fi

[ -s /www/index.html ] || ln -s /www/luci2.html /www/index.html
