#!/bin/sh /etc/rc.common
# Copyright (C) 2015 Patrick Grimm

START=98
SERVER="ffwizard_autoconf"
BIN="/usr/sbin/ffwizard_autoconf"


start() {
	boot=$(uci_get ffwizard autoconf boot "0")
	[ "$boot" == "0" ] && return
	start-stop-daemon -S -x $BIN \
		-p /var/run/${SERVER}.pid \
		-m -b --

	uci_set ffwizard autoconf boot 0
	uci_commit ffwizard
}

restart() {
	start
}
