#!/bin/sh /etc/rc.common
# Copyright (C) 2015 Patrick Grimm

START=99
SERVER="ffwizard"
BIN="/usr/sbin/ffwizard"


start() {
	enabled=$(uci_get ffwizard ffwizard enabled "0")
	[ "$enabled" == "0" ] && return
	start-stop-daemon -S -x $BIN \
		-p /var/run/${SERVER}.pid \
		-m -b --
	uci_set ffwizard ffwizard enabled 0
	uci_commit ffwizard
}

restart() {
	start
}
