#!/bin/sh /etc/rc.common
# Copyright (C) 2015 Patrick Grimm

START=99
SERVER="ffwizard"
BIN="/usr/sbin/ffwizard"


start() {
	. /lib/functions/network.sh
	config_load ffwizard
	config_get enabled ffwizard enabled "0"
	[ "$enabled" == "0" ] && return
	start-stop-daemon -S -x $BIN \
		-p /var/run/${SERVER}.pid \
		-m -b --
	uci set ffwizard.ffwizard.enabled=0
	uci commit
}

restart() {
	start
}
