#!/bin/sh

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

log_ffwizard() {
	logger -s -t ffwizard $@
}

wdir="/etc/ffwizard.d"
[ -d $wdir ] || return 0
files="$(ls $wdir | sort)"
[ -z "$files" ] && return 0
for file in $files; do
	log_ffwizard "procesing $file"
	. "$wdir/$file"
done

ubus call uci "reload_config"

#TODO reload config does not work for olsrd2, uhttpd, dnsmasq, crontab
sleep 3
[ -f /etc/init.d/olsrd2 ] && /etc/init.d/olsrd2 restart
[ -f /etc/init.d/uhttpd ] && /etc/init.d/uhttpd restart
[ -f /etc/init.d/dnsmasq ] && /etc/init.d/dnsmasq restart
[ -f /etc/init.d/crontab ] && /etc/init.d/crontab restart
