#!/bin/sh

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

log_ffwizard() {
	logger -s -t ffwizard $@
}

wdir="/etc/ffwizard.d"
[ -d $wdir ] || return 0
files="$(ls $wdir | sort)"
[ -z "$files" ] && return 0
for file in $files; do
	log_ffwizard "procesing $file"
	. "$wdir/$file"
done

#ubus call uci "reload_config"

#TODO reload config does not work for olsrd2, uhttpd, dnsmasq, crontab
#sleep 3
log_ffwizard "restart network"
ubus call rc init '{"name":"network","action":"restart"}' || /etc/init.d/network restart
sleep 3
log_ffwizard "restart olsrd"
ubus call rc init '{"name":"olsrd2","action":"restart"}' || /etc/init.d/olsrd2 restart
sleep 3
log_ffwizard "restart uhttpd"
ubus call rc init '{"name":"uhttpd","action":"restart"}' || /etc/init.d/uhttpd restart
sleep 3
log_ffwizard "restart dnsmasq"
ubus call rc init '{"name":"dnsmasq","action":"restart"}' || /etc/init.d/dnsmasq restart
sleep 3
log_ffwizard "restart cron"
ubus call rc init '{"name":"cron","action":"restart"}' || /etc/init.d/crond restart
sleep 3
log_ffwizard "exit"
