#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99

setup_ether() {
	local cfg="$1"
	[ "$cfg" == "loopback" ] && return
	[ "$cfg" == "fflandhcp" ] && return
	[ "$cfg" == "lan6" ] && return
	[ "$cfg" == "wan6" ] && return
	[ "$cfg" == "wwan" ] && return
	[ "$cfg" == "wlan0" ] && return
	[ "$cfg" == "wlan1" ] && return
	[ "$cfg" == "wlan2" ] && return
	[ "$cfg" == "radio0_mesh" ] && return
	[ "$cfg" == "radio1_mesh" ] && return
	[ "$cfg" == "radio2_mesh" ] && return
	if ! uci_get ffwizard $cfg >/dev/null ; then
		uci_add ffwizard ether "$cfg"
	fi
	#Disable wan by default?
	if [ "$cfg" == "wan" ] ; then
		uci_set ffwizard $cfg enabled "0"
	else
		uci_set ffwizard $cfg enabled "1"
	fi
	uci_set ffwizard $cfg device $cfg
	uci_set ffwizard $cfg dhcp_br "0"
	uci_set ffwizard $cfg olsr_mesh "1"
	uci_set ffwizard $cfg bat_mesh "0"
}

setup_wifi() {
	local cfg="$1"
	#cut radio to get the phy index
	local idx="$(echo $cfg | cut -c 6-)"
	if ! uci_get ffwizard $cfg >/dev/null ; then
		uci_add ffwizard wifi "$cfg"
	fi
	uci_set ffwizard $cfg enabled "1"
	uci_set ffwizard $cfg phy_idx $idx
	uci_set ffwizard $cfg olsr_mesh "1"
	uci_set ffwizard $cfg bat_mesh "0"
	uci_set ffwizard $cfg vap "1"
	uci_set ffwizard $cfg vap_br "1"
}

start_autoconf() {
	config_load wireless
	config_foreach setup_wifi wifi-device
	config_load network
	config_foreach setup_ether interface
	# Reset firstboot flag
	uci_set ffwizard autoconf firstboot 0
	uci_set ffwizard ffwizard enabled 0
	uci_commit ffwizard
	/usr/sbin/ffwizard_autoconf
	/usr/sbin/ffwizard
}

start_ffwizard() {
	uci_set ffwizard ffwizard enabled 0
	uci_commit ffwizard
	/usr/sbin/ffwizard
}

start() {
	logger -s -t ffwizard_autoconf "Start Service"
	firstboot=$(uci_get ffwizard autoconf firstboot "0")
	enabled=$(uci_get ffwizard ffwizard enabled "0")
	if [ "$firstboot" == "1" ] ; then
		start_autoconf
	elif [ "$enabled" == "1" ] ; then
		start_ffwizard
	fi
}
