#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99

start_ffwizard() {
	enabled=$(uci_get ffwizard ffwizard enabled "0")
	[ "$enabled" == "0" ] && return
	/usr/sbin/ffwizard
}

start() {
	logger -s -t ffwizard_init "Start Service"
	start_ffwizard
}
