#!/bin/sh /etc/rc.common
# Copyright (C) 2015 Patrick Grimm

START=98
USE_PROCD=1

validate_autoconf_section()
{
	uci_validate_section ffwizard autoconf "${1}" \
		'firstboot:bool'
}


setup_ether() {
	local cfg="$1"
	[ "$cfg" == "loopback" ] && return
	[ "$cfg" == "fflandhcp" ] && return
	[ "$cfg" == "lan6" ] && return
	[ "$cfg" == "wan6" ] && return
	[ "$cfg" == "wwan" ] && return
	[ "$cfg" == "wlan0" ] && return
	[ "$cfg" == "wlan1" ] && return
	[ "$cfg" == "wlan2" ] && return
	[ "$cfg" == "radio0_mesh" ] && return
	[ "$cfg" == "radio1_mesh" ] && return
	[ "$cfg" == "radio2_mesh" ] && return
	if ! uci_get ffwizard $cfg >/dev/null ; then
		uci_add ffwizard ether "$cfg"
	fi
	#Disable wan by default?
	if [ "$cfg" == "wan" ] ; then
		uci_set ffwizard $cfg enabled "0"
	else
		uci_set ffwizard $cfg enabled "1"
	fi
	uci_set ffwizard $cfg device $cfg
	uci_set ffwizard $cfg dhcp_br "0"
	uci_set ffwizard $cfg olsr_mesh "1"
	uci_set ffwizard $cfg bat_mesh "0"
}

setup_wifi() {
	local cfg="$1"
	#cut radio to get the phy index
	local idx="$(echo $cfg | cut -c 6-)"
	if ! uci_get ffwizard $cfg >/dev/null ; then
		uci_add ffwizard wifi "$cfg"
	fi
	uci_set ffwizard $cfg enabled "1"
	uci_set ffwizard $cfg phy_idx $idx
	uci_set ffwizard $cfg olsr_mesh "1"
	uci_set ffwizard $cfg bat_mesh "0"
	uci_set ffwizard $cfg vap "1"
	uci_set ffwizard $cfg vap_br "1"
}


start_autoconf() {
	firstboot=$(uci_get ffwizard autoconf firstboot "0")
	[ "$firstboot" == "0" ] && return
	config_load wireless
	config_foreach setup_wifi wifi-device
	config_load network
	config_foreach setup_ether interface
	# Reset firstboot flag
	uci_set ffwizard autoconf firstboot 0
	uci_commit ffwizard
	/usr/sbin/ffwizard_autoconf
}

reload_service() {
	logger -s -t ffwizard_autoconf "Reload Service"
	start_autoconf
}

service_triggers()
{
	procd_open_trigger
	procd_add_config_trigger "config.change" ffwizard /etc/init.d/ffwizard_autoconf reload
	procd_close_trigger

	procd_open_validate
	validate_autoconf_section
	procd_close_validate
}

start_service() {
	logger -s -t ffwizard_autoconf_init "Start Service"
	procd_set_param watch ffwizard
	start_autoconf
}
